### ISSUE TITLE
Dragonglue library

### ISSUE THREAD

**Issue by sjlnk** [drocco007/vox_commands#1]
What is this dragonglue library?

How do you forward context (application/title etc) from Linux to dragonfly (on Windows)?

I see you are using mechanisms built-in into dragonfly to load/unload grammars upon context switch but I fail to understand how are these contexts read from the Linux host.

**Comment by drocco007** [comment]
Hi!

> What is this dragonglue library?

I started moving some stuff around at some point trying to get the Dragon/Linux interface bits better organized, but the bridge pieces are still pretty rough. The important bit of `dragonglue` is [this context class](https://gist.github.com/drocco007/f8d62ec1a8ee0d0d4ec6f4de05cb5361), which uses a global variable from `natlinkmain` to set the current application for dragonfly (normally dragonfly pulls the information from Windows).


> How do you forward context (application/title etc) from Linux to dragonfly (on Windows)?

Two other pieces are important here. The first is a modified `natlinkmain` to which I've added a background thread that listens for `COMMAND_BROADCAST_TITLE` messages and stores the title in the global variable referenced above:

    linux_module = None


    def listen_for_title_changes():
        import zmq

        context = zmq.Context()
        socket = context.socket(zmq.SUB)

        socket.connect("tcp://vmhost:5556")
        socket.setsockopt(zmq.SUBSCRIBE, COMMAND_BROADCAST_TITLE)


        def listener():
            global linux_module

            while True:
                message = socket.recv()[1:]
                title, application = message.split(RECORD_SEPARATOR)

                module = application.lower().replace(' ', '_')

                print module
                linux_module = module

        thread = Thread(target=listener)
        thread.daemon = True
        thread.start()
        return thread 

The other part is already in Vox: [this GTK process](https://github.com/drocco007/vox_linux/blob/master/vox/titles.py) hooks an event handler into the window manager that listens for `active-window-changed` events, pushing `COMMAND_BROADCAST_TITLE` messages onto Vox's ØMQ message bus with the new application title. The modified `natlinkmain` thread picks up those messages and saves the current Linux window title for the next voice utterance. The `LinuxAppContext` class in turn uses that value to establish the application context for Dragonfly which, as you noted, allows me to use much of the existing machinery it makes available.

I'm glad you're digging into this and trying to understand it, so please continue asking questions about any of the confusing bits. :) Don't be afraid to critique, either: there is lots of room for improvement here! :)

**Comment by sjlnk** [comment]
Thanks for the detailed answer @drocco007 !
